name: Build
on: [ push ]

jobs:
  build:
    timeout-minutes: 5
    runs-on: zondax-runners
    container:
      image: node:20-slim
      options: --tty
    steps:
      - name: Install deps
        run: |
          apt update
          apt install -y git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run formatter
        run: yarn format
      - name: Run linter
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run Tests
        run: yarn test
